# Generated by Django 5.0.4 on 2024-11-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
