# Generated by Django 5.0.4 on 2024-11-23 15:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_alter_competition_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
