# Generated by Django 5.0.4 on 2024-11-23 17:06

import FisherPoint.validators.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_competition_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100, message='Description must be at least 100 characters')]),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10, message='Title must be at least 10 characters'), FisherPoint.validators.validators.competition_title_validator]),
        ),
    ]
